import type { BeerOffer, Location } from "@/lib/types";

export const locations: Location[] = [
  {
    id: "pogue-mahone",
    name: "Pogue Mahone Irish Pub",
    locationType: "pub",
    district: "Altstadt",
    address: "Bergstrasse 19, 24103 Kiel",
  },
  {
    id: "hafenkante-bar",
    name: "Hafenkante Bar",
    locationType: "bar",
    district: "Duesternbrook",
    address: "Kiellinie 99, 24105 Kiel",
  },
  {
    id: "foerde-brauhaus",
    name: "Foerde Brauhaus",
    locationType: "restaurant",
    district: "Vorstadt",
    address: "Kehdenstrasse 12, 24103 Kiel",
  },
  {
    id: "marktfrisch-kiel",
    name: "Marktfrisch Kiel",
    locationType: "supermarket",
    district: "Gaarden",
    address: "Schoenberger Strasse 4, 24148 Kiel",
  },
];

export const beerOffers: BeerOffer[] = [
  {
    id: "offer-001",
    brand: "Guinness",
    variant: "Stout",
    sizeMl: 568,
    serving: "tap",
    priceEur: 6.9,
    locationId: "pogue-mahone",
  },
  {
    id: "offer-002",
    brand: "Kilkenny",
    variant: "Red Ale",
    sizeMl: 568,
    serving: "tap",
    priceEur: 6.6,
    locationId: "pogue-mahone",
  },
  {
    id: "offer-003",
    brand: "Becks",
    variant: "Pils",
    sizeMl: 500,
    serving: "bottle",
    priceEur: 4.2,
    locationId: "hafenkante-bar",
  },
  {
    id: "offer-004",
    brand: "Astra",
    variant: "Pils",
    sizeMl: 330,
    serving: "can",
    priceEur: 2.7,
    locationId: "hafenkante-bar",
  },
  {
    id: "offer-005",
    brand: "Flensburger",
    variant: "Pils",
    sizeMl: 400,
    serving: "tap",
    priceEur: 5.2,
    locationId: "foerde-brauhaus",
  },
  {
    id: "offer-006",
    brand: "Erdinger",
    variant: "Hefeweizen",
    sizeMl: 500,
    serving: "bottle",
    priceEur: 5.4,
    locationId: "foerde-brauhaus",
  },
  {
    id: "offer-007",
    brand: "Holsten",
    variant: "Pils",
    sizeMl: 500,
    serving: "can",
    priceEur: 1.39,
    locationId: "marktfrisch-kiel",
  },
  {
    id: "offer-008",
    brand: "Guinness",
    variant: "Stout",
    sizeMl: 440,
    serving: "can",
    priceEur: 2.29,
    locationId: "marktfrisch-kiel",
  },
];
