version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-minor-and-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-dev-minor-and-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"
    # Automatically label dependabot PRs
    labels:
      - "dependencies"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "cargo"
    directory: "/backend/crates/api"
    schedule:
      interval: "daily"
    groups:
      cargo:
        patterns:
          - "*"
    labels:
      - "dependencies"
