apiVersion: batch/v1
kind: Job
metadata:
  name: kiebex-migrate
  namespace: kiebex
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/h1ghbre4k3r/kiebex-migrate:86a4a2076112174da50211e76d1f95d0e9760214
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              node node_modules/prisma/build/index.js migrate deploy &&
              node prisma/seed-admin.mjs
          envFrom:
            - secretRef:
                name: kiebex-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
