apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiebex-storage
  namespace: kiebex-pr-44
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kiebex-pr-44
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kiebex-storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kiebex-pr-44
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
