apiVersion: v1
kind: Secret
metadata:
  name: kiebex-secret
  namespace: kiebex-pr-${PR_NUMBER}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/kiel_beer_index
  APP_URL: https://pr-${PR_NUMBER}.review.kiel.beer
  ADMIN_EMAIL: ${ADMIN_EMAIL}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}
