apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kiebex-ingress
  namespace: kiebex-pr-35
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pr-35.review.kiel.beer`)
      kind: Rule
      services:
        - name: kiebex-service
          port: 80
  tls:
    certResolver: le
