---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kiebex-secret
  namespace: kiebex
spec:
  encryptedData:
    DATABASE_URL: AgDK52wiZ3rU1BdHuYf4BD8qCvNoF6Rrxki8VJGGinYEvV0ECAKqUgQEXqZh6hN3GPxBCiyrZ1Px6Pcy0m6y2YqLU3CzvJLE7OfNxTKLMBYPLousYKh0Kr0S0A1cNTqkBgFf5ODpq88U/z1QnKy6AVTaaHM+K5ST6oItrqxPQO/W+ZyoQWUFMEyS+2zUTSLfL3tl2MmxaY32zXZsJoD3CC0HNYGll+12BR2/z0xXPL71HyjSoavPJWoaSNZTvSyaKpLz/TvctydodmmGRA3EJ9aJN15PkTe9nvzhdydxg9wdzhzSqxFBou6lKTYybpq3yM6JYNFimnpzuSMDJvsBzpaDj7xEriyz9n6jileez5TagAcsvzehiAYBVobt8yF3FOX9EQlWB7lL3aQfToXhv1nNgAmHsUdAJLoS7hKh4ykynA4Kmy1Ni3aA3sHbJro52fpWBAfkZvycZW0FEQuDNK13vBtOsREoAkD8c5G5h7In64MODSEAc8Nlfttbod5GQw9yi1OrTZn2Q6/sMzI/sucBpOwmgdo1Wt1M3/mXsBs5j+ddllynF0AOphJM3BJrLGXUxC8UHJE9J7RSBwmxDmVV7/1v2VpGIZrviBc+euinG0xUeB8LLyZ61yMA8YRimLgkDS6HvXCkbTD88wWQ/l1pAzY/APJBHepwkQfSEvCtu0Fv3/3IfMgQmTS17X3RCtinnk85CIZzGxsj9yDX/+C9eHph6eaizaavhHRKVd8DinZOawuRze1zsG+MY8JuCYWl017MGJVNNY5+QpbaDmq/yxYSg/0SdpQVqVYqRb5HzZ97QSRebvzqbsumu48dmRUnZFOHqlykk58zjtoCo7krGLLcqbdvhiR0DuJCc7eVRY8Sv8w4+hnsYw==
  template:
    metadata:
      name: kiebex-secret
      namespace: kiebex
