apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kiebex
  name: kiebex-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kiebex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kiebex-storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kiebex
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
