apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kiebex-pr-32
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: kiel_beer_index
