apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: review-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/h1ghbre4k3r/kiebex
        revision: deploy
        directories:
          - path: review-apps/*
  template:
    metadata:
      name: "review-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/h1ghbre4k3r/kiebex
        targetRevision: deploy
        path: "review-apps/{{path.basename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "kiebex-{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
