apiVersion: v1
kind: Secret
metadata:
  name: kiebex-secret
  namespace: kiebex-pr-41
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/kiel_beer_index
  APP_URL: https://pr-41.review.kiel.beer
  ADMIN_EMAIL: admin@review.kiel.beer
  ADMIN_PASSWORD: review
